USE movies;

--1--
SELECT M.TITLE, ME.NAME
FROM MOVIE M
JOIN MOVIEEXEC ME ON M.PRODUCERC# = ME.CERT#
WHERE M.PRODUCERC#=(SELECT PRODUCERC# FROM MOVIE WHERE TITLE = 'Star Wars');

--2--
SELECT DISTINCT ME.NAME
FROM MOVIE M
JOIN MOVIEEXEC ME ON M.PRODUCERC# = ME.CERT#
WHERE M.TITLE IN (SELECT MOVIETITLE FROM STARSIN WHERE STARNAME = 'Harrison Ford');

--3--
SELECT DISTINCT M.STUDIONAME, S.STARNAME
FROM MOVIE M
JOIN STARSIN S ON M.TITLE = S.MOVIETITLE
ORDER BY M.STUDIONAME;

--4--
SELECT SI.STARNAME, ME.NETWORTH, M.TITLE
FROM STARSIN SI
JOIN MOVIE M ON SI.MOVIETITLE = M.TITLE
JOIN MOVIEEXEC ME ON M.PRODUCERC# = ME.CERT#
WHERE ME.NETWORTH IN (SELECT MAX(NETWORTH) FROM MOVIEEXEC)

--5--
SELECT MS.NAME, S.MOVIETITLE
FROM MOVIESTAR MS
LEFT JOIN STARSIN S ON S.STARNAME =MS.NAME
WHERE MS.NAME NOT IN (SELECT STARNAME FROM STARSIN); 


use pc;
--1--
select *
from product p
where p.model not in(select model from pc)
and  p.model not in(select model from laptop)
and  p.model not in(select model from printer);

--2--
select p.maker
from product p
join laptop l on l.model = p.model
intersect
select p.maker
from product p
join printer pr on pr.model = p.model;

--3--
select distinct l.hd 
from laptop l
join laptop l2 on l.hd = l2.hd
where l.model !=l2.model;

--4--
select model
from pc
where model not in (select model from product);

use ships;

--1--
SELECT S.NAME, S.CLASS, S.LAUNCHED, C.CLASS,C.TYPE, C.COUNTRY, C.NUMGUNS, C.BORE,
C.DISPLACEMENT
FROM SHIPS S
JOIN CLASSES C ON S.CLASS = C.CLASS;

--2--
SELECT S.NAME, S.CLASS, S.LAUNCHED, C.CLASS,C.TYPE, C.COUNTRY, C.NUMGUNS, C.BORE,
C.DISPLACEMENT
FROM SHIPS S
FULL JOIN CLASSES C ON S.CLASS = C.CLASS;

--3--
SELECT C.COUNTRY, S.NAME
FROM CLASSES C
JOIN SHIPS S ON S.CLASS = C.CLASS
WHERE S.NAME NOT IN (SELECT SHIP FROM OUTCOMES)
ORDER BY COUNTRY;

--4--
SELECT S.NAME
FROM SHIPS S
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE S.LAUNCHED = 1916 AND C.NUMGUNS>=7;

--5--
SELECT O.SHIP, B.NAME, B.DATE
FROM OUTCOMES O
JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE O.RESULT = 'sunk'
ORDER BY B.NAME;

--6--
SELECT S.NAME, C.DISPLACEMENT, S.LAUNCHED
FROM SHIPS S
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE S.NAME = S.CLASS;

--7--
SELECT C.*
FROM CLASSES C
FULL JOIN SHIPS S ON S.CLASS = C.CLASS
WHERE C.CLASS NOT IN ( SELECT CLASS FROM SHIPS); 

--8--
SELECT S.NAME, C.DISPLACEMENT, C.NUMGUNS, O.RESULT
FROM SHIPS S
JOIN CLASSES C ON C.CLASS = S.CLASS
JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.BATTLE =  'North Atlantic';

