USE MOVIES;

--1--
SELECT М.TITLE, М.YEAR, М.LENGTH
FROM MOVIE М
WHERE YEAR < 2000 AND 
(LENGTH>120 OR LENGTH IS NULL);

--2--
SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE > 1948
ORDER BY NAME DESC;

--3--
SELECT M.STUDIONAME, COUNT(STARNAME) AS num_actors
FROM MOVIE M
JOIN STARSIN S ON S.MOVIETITLE = M.TITLE
GROUP BY M.STUDIONAME;

--4--
SELECT STARNAME, COUNT(MOVIETITLE) AS num_movies
FROM STARSIN
GROUP BY STARNAME;

--5--
SELECT T2.STUDIONAME,T1.TITLE, T2.YEAR
FROM (SELECT DISTINCT STUDIONAME, MAX(YEAR) AS year 
FROM MOVIE
GROUP BY STUDIONAME) T2
JOIN MOVIE T1 ON T1.STUDIONAME = T2.STUDIONAME AND T1.YEAR = T2.year;

--6--
SELECT TOP 1 NAME
FROM MOVIESTAR
WHERE GENDER = 'M' 
ORDER BY BIRTHDATE DESC;

--7-- ???
SELECT M.STUDIONAME, S.STARNAME, COUNT(S.STARNAME) AS num_movies
FROM MOVIE M
JOIN STARSIN S ON S.MOVIETITLE = M.TITLE
GROUP BY S.STARNAME, M.STUDIONAME
HAVING COUNT(S.STARNAME) >= 2;

--8--
SELECT S.MOVIETITLE, S.MOVIEYEAR, COUNT(S.STARNAME) AS num_actors
FROM STARSIN S
GROUP BY S.MOVIETITLE, S.MOVIEYEAR
HAVING COUNT(S.MOVIETITLE) > 2;

USE SHIPS;

--1--
SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE SHIP LIKE 'C%' OR SHIP LIKE 'K%';

--2-- ???
SELECT O.SHIP, C.COUNTRY, C.BORE, C.CLASS
FROM OUTCOMES O
JOIN SHIPS S ON S.NAME = O.SHIP
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE RESULT NOT LIKE 'sunk' OR C.TYPE = 'bc'

SELECT *
FROM SHIPS;

SELECT *
FROM BATTLES;

SELECT *
FROM OUTCOMES;

SELECT *
FROM CLASSES;


USE PC;

--1--
SELECT MODEL, CODE, SCREEN
FROM LAPTOP
WHERE SCREEN = 15 OR SCREEN = 11;

--2-- ???
SELECT P.MODEL
FROM PRODUCT P
WHERE TYPE = 'PC' AND 
P.MAKER IN 
(SELECT P.MAKER 
FROM PRODUCT P
WHERE --P.TYPE = 'Laptop' AND 
MODEL IN 
(SELECT MODEL 
FROM PC 
WHERE PRICE < (SELECT MIN(PRICE) FROM LAPTOP)));


SELECT *
FROM PC;

SELECT *
FROM PRODUCT;

SELECT *
FROM LAPTOP;

--SELECT *
--FROM MOVIEEXEC;

--SELECT *
--FROM STUDIO;